### ISSUE TITLE
Confusing Project Name

### ISSUE THREAD

**Issue by devAgam** [sinclairnick/brail#26]
Took this from Reddit User [Swamptor](https://www.reddit.com/user/Swamptor/)

> I just want to say, that while the project looks cool, it seems like a bad idea to name your library after a critical accessibility feature that it has nothing to do with.

And i feel like this should be adjusted to provide a little more clarity

**Comment by leavism** [comment]
I get that Brail is spelled differently from braille, but the point of confusion will persist for the entirety of this framework's lifetime simply because it's pronounced the exact same way. Highly recommend changing the name because I think a lot of people are going to think  of accessibility when they hear Brail, not writing emails.

**Comment by sinclairnick** [comment]
For now the functionality of the toolkit is whats primarily important. If the name continues to confuse people I will consider renaming, but until then attention should be spent on delivering valuable features and fixed

**Comment by devAgam** [comment]
I believe it should be renamed now rather than later, because when the project gains some steam it would be a bigger issue.
